#include <kern_datatypes.hpp>

#ifndef _BOARD_HPP_
#define _BOARD_HPP_

typedef enum DeviceType
{
	DEVICE_TYPE_ERROR = 0,
	DEVICE_TYPE_FLASH,
	DEVICE_TYPE_CPU_PERIPHERAL,
	DEVICE_TYPE_GIC_DIST,
	DEVICE_TYPE_GIC_CPU,
	DEVICE_TYPE_UART,
	DEVICE_TYPE_RTC,
	DEVICE_TYPE_GPIO,
	DEVICE_TYPE_SECURE_UART,
	DEVICE_TYPE_SECURE_GPIO,
	DEVICE_TYPE_MMIO,
	DEVICE_TYPE_PCIE_MMIO,
	DEVICE_TYPE_PCIE_PIO,
	DEVICE_TYPE_PCIE_ECAM,
}DeviceType;

#endif